import type { Lesson } from './types'
import type { Goal } from './grade'
import { POS } from './project'

const all = (of: Goal[]): Goal => ({ type: 'all', of })

export const LESSONS: Lesson[] = [
  {
    id: 'move',
    chapter: 'Modes',
    title: 'Moving around',
    objective: 'Land on the X.',
    explanation:
      'Normal mode is for moving. h j k l step left, down, up, and right, one character at a time. The cursor is a block while you are in normal mode. You are not typing text yet.',
    keys: ['j', 'j', 'l', 'l'],
    file: 'scratch.ts',
    content: 'Move with hjkl.\nDown two lines.\n  X marks it.',
    cursor: { line: 0, col: 0 },
    project: false,
    enable: {},
    goal: { type: 'cursor', line: 2, col: 2 },
  },
  {
    id: 'insert',
    chapter: 'Modes',
    title: 'Insert and escape',
    objective: 'Add the word hello, then leave insert mode.',
    explanation:
      'i enters insert mode at the cursor, and Esc returns to normal. A jumps to the end of the line and inserts there. The cursor becomes a thin bar in insert mode. Every editing command in the rest of the tutor starts and ends in normal mode.',
    keys: ['A', 'h', 'e', 'l', 'l', 'o', '<Esc>'],
    file: 'scratch.ts',
    content: 'say ',
    cursor: { line: 0, col: 0 },
    project: false,
    enable: {},
    goal: all([
      { type: 'includes', text: 'hello' },
      { type: 'mode', mode: 'normal' },
    ]),
  },
  {
    id: 'append',
    chapter: 'Modes',
    title: 'Around the cursor',
    objective: 'Append an exclamation mark to the line.',
    explanation:
      'a inserts after the cursor, A at the end of the line, I at the first non-blank character. o opens a line below, O above. A is the shortest path when the new text belongs at the end.',
    keys: ['A', '!', '<Esc>'],
    file: 'scratch.ts',
    content: 'ready',
    cursor: { line: 0, col: 0 },
    project: false,
    enable: {},
    goal: { type: 'buffer', text: 'ready!' },
  },
  {
    id: 'replace',
    chapter: 'Modes',
    title: 'Replace and undo',
    objective: 'Turn colur into color.',
    explanation:
      'r replaces the character under the cursor and stays in normal mode. u undoes the last change. Ctrl-r redoes it. Use r when one character is wrong and you do not need insert mode.',
    keys: ['3', 'l', 'r', 'o'],
    file: 'scratch.ts',
    content: 'colur',
    cursor: { line: 0, col: 0 },
    project: false,
    enable: {},
    goal: { type: 'buffer', text: 'color' },
  },
  {
    id: 'words',
    chapter: 'Motions',
    title: 'Words',
    objective: 'Land on the b in beta.',
    explanation:
      'w moves to the start of the next word, b to the start of the previous word, e to the end of the word. 0 jumps to the first column, ^ to the first non-blank, $ to the end of the line. Words are how Neovim measures most edits.',
    keys: ['w'],
    file: 'scratch.ts',
    content: 'alpha beta gamma',
    cursor: { line: 0, col: 0 },
    project: false,
    enable: {},
    goal: { type: 'cursor', line: 0, col: 6 },
  },
  {
    id: 'find',
    chapter: 'Motions',
    title: 'Find a character',
    objective: 'Land on the q.',
    explanation:
      'f jumps to the next occurrence of a character on this line. t stops just before it. F and T search backward. ; repeats the find, , reverses it. It is the fastest way across a line when you can see the character.',
    keys: ['f', 'q'],
    file: 'scratch.ts',
    content: 'the quick brown fox',
    cursor: { line: 0, col: 0 },
    project: false,
    enable: {},
    goal: { type: 'cursor', line: 0, col: 4 },
  },
  {
    id: 'counts',
    chapter: 'Motions',
    title: 'Counts',
    objective: 'Land on the line that says land.',
    explanation:
      'A count repeats the next motion. 6j moves down six lines. gg goes to the first line, G to the last, and 7gg goes to line 7. Counts work on almost every motion and operator you will meet.',
    keys: ['6', 'j'],
    file: 'scratch.ts',
    content: 'one\ntwo\nthree\nfour\nfive\nsix\nland\neight',
    cursor: { line: 0, col: 0 },
    project: false,
    enable: {},
    goal: { type: 'cursor', line: 6, col: 0 },
  },
  {
    id: 'search',
    chapter: 'Motions',
    title: 'Search',
    objective: 'Land on the second target.',
    explanation:
      '/ starts a search. Enter jumps to the first match after the cursor. n repeats it forward, N backward. Search is how you move when the target is off screen. The matches stay highlighted.',
    keys: ['/', 't', 'a', 'r', 'g', 'e', 't', '<CR>', 'n'],
    file: 'scratch.ts',
    content: 'one target\ntwo\nthree target',
    cursor: { line: 0, col: 0 },
    project: false,
    enable: {},
    goal: { type: 'cursor', line: 2, col: 6 },
  },
  {
    id: 'change',
    chapter: 'Grammar',
    title: 'Operator and motion',
    objective: 'Change two into both.',
    explanation:
      'd deletes and c changes. Both wait for a motion. dw deletes a word, cw changes it and drops you into insert. The shape is always verb then noun: delete this word, change until the end of the line. Esc finishes the change.',
    keys: ['w', 'c', 'w', 'b', 'o', 't', 'h', '<Esc>'],
    file: 'scratch.ts',
    content: 'one two three',
    cursor: { line: 0, col: 0 },
    project: false,
    enable: {},
    goal: { type: 'buffer', text: 'one both three' },
  },
  {
    id: 'yank',
    chapter: 'Grammar',
    title: 'Lines and put',
    objective: 'Duplicate the first line.',
    explanation:
      'yy yanks the whole line, dd deletes it, p puts the yanked text below the cursor, P puts it above. D, C, and Y act on the rest of the line, the same way $ does. Linewise text keeps its own line when you put it back.',
    keys: ['y', 'y', 'p'],
    file: 'scratch.ts',
    content: 'red\nblue\ngreen',
    cursor: { line: 0, col: 0 },
    project: false,
    enable: {},
    goal: { type: 'buffer', text: 'red\nred\nblue\ngreen' },
  },
  {
    id: 'dot',
    chapter: 'Grammar',
    title: 'Repeat the change',
    objective: 'Turn every foo into bar.',
    explanation:
      '. repeats the last change, not the last motion. Change the first word, move to the next with w, then press . . The motion between repeats is yours. The change replays at the new cursor.',
    keys: ['c', 'w', 'b', 'a', 'r', '<Esc>', 'w', '.', 'w', '.'],
    file: 'scratch.ts',
    content: 'foo foo foo',
    cursor: { line: 0, col: 0 },
    project: false,
    enable: {},
    goal: all([
      { type: 'buffer', text: 'bar bar bar' },
      { type: 'event', name: 'dot' },
    ]),
  },
  {
    id: 'visual',
    chapter: 'Grammar',
    title: 'Visual mode',
    objective: 'Delete the middle line.',
    explanation:
      'v selects characters, V selects lines. A motion extends the selection. d deletes it and y yanks it. Visual mode is the same operator grammar with the noun highlighted first. Esc cancels the selection.',
    keys: ['j', 'V', 'd'],
    file: 'scratch.ts',
    content: 'alpha\nbeta\ngamma',
    cursor: { line: 0, col: 0 },
    project: false,
    enable: {},
    goal: { type: 'buffer', text: 'alpha\ngamma' },
  },
  {
    id: 'indent',
    chapter: 'Grammar',
    title: 'Indent',
    objective: 'Indent the middle line.',
    explanation:
      '>> indents the current line. << outdents it. A count, or a visual selection, covers more lines. The tutor indents by two spaces, which is what this buffer is aiming for.',
    keys: ['j', '>', '>'],
    file: 'scratch.ts',
    content: 'function greet() {\nconst message = "hi"\n}',
    cursor: { line: 0, col: 0 },
    project: false,
    enable: {},
    goal: { type: 'buffer', text: 'function greet() {\n  const message = "hi"\n}' },
  },
  {
    id: 'substitute',
    chapter: 'Grammar',
    title: 'Substitute',
    objective: 'Replace the first foo on this line.',
    explanation:
      ': opens the command line. :s/foo/bar/ replaces the first foo on the current line. A trailing g replaces every match on the line, and :%s does the whole file. This lesson only needs the first match.',
    keys: [':', 's', '/', 'f', 'o', 'o', '/', 'b', 'a', 'r', '/', '<CR>'],
    file: 'scratch.ts',
    content: 'foo foo foo',
    cursor: { line: 0, col: 0 },
    project: false,
    enable: {},
    goal: all([
      { type: 'buffer', text: 'bar foo foo' },
      { type: 'event', name: 'cmd:s' },
    ]),
  },
  {
    id: 'quotes',
    chapter: 'Objects',
    title: 'Inside quotes',
    objective: 'Change Ada to Lynn.',
    explanation:
      'Text objects are nouns you can use with any operator. ci" changes inside the quotes, ca" includes the quotes. The cursor can sit anywhere in the pair. The same idea works for single quotes.',
    keys: ['f', 'A', 'c', 'i', '"', 'L', 'y', 'n', 'n', '<Esc>'],
    file: 'scratch.ts',
    content: 'const name = "Ada"',
    cursor: { line: 0, col: 0 },
    project: false,
    enable: {},
    goal: { type: 'buffer', text: 'const name = "Lynn"' },
  },
  {
    id: 'parens',
    chapter: 'Objects',
    title: 'Inside parens',
    objective: 'Change Ada to Lynn.',
    explanation:
      'ci( changes inside parentheses. ca( includes them. i{ and a{ do the same for braces, and ib is another way to say i(. % jumps between the matching bracket when you only want to move.',
    keys: ['f', 'A', 'c', 'i', '(', 'L', 'y', 'n', 'n', '<Esc>'],
    file: 'scratch.ts',
    content: 'greet(Ada)',
    cursor: { line: 0, col: 0 },
    project: false,
    enable: {},
    goal: { type: 'buffer', text: 'greet(Lynn)' },
  },
  {
    id: 'inner-word',
    chapter: 'Objects',
    title: 'Inner word',
    objective: 'Delete BETA and leave the spaces.',
    explanation:
      'iw is the word under the cursor, with no surrounding space. aw is the word plus the following space, or the space before it if there is none after. diw is the precise delete. daw is the one you want when the gap should close.',
    keys: ['w', 'd', 'i', 'w'],
    file: 'scratch.ts',
    content: 'alpha BETA gamma',
    cursor: { line: 0, col: 0 },
    project: false,
    enable: {},
    goal: { type: 'buffer', text: 'alpha  gamma' },
  },
  {
    id: 'paragraph',
    chapter: 'Objects',
    title: 'Paragraphs',
    objective: 'Delete the middle paragraph.',
    explanation:
      'A paragraph is a block of non-blank lines. ip selects it. ap also takes a neighboring blank line, so the buffer does not keep a double gap. } and { move between paragraphs. dap is the usual way to drop one.',
    keys: ['}', 'd', 'a', 'p'],
    file: 'scratch.ts',
    content: 'keep me\n\ndrop this\nparagraph\n\ntail',
    cursor: { line: 0, col: 0 },
    project: false,
    enable: {},
    goal: { type: 'buffer', text: 'keep me\n\ntail' },
  },
  {
    id: 'registers',
    chapter: 'Power',
    title: 'Named registers',
    objective: 'Yank the first line into register a, then put it at the bottom.',
    explanation:
      '" names a register before a yank, delete, or put. "ayy yanks the line into a. "ap puts it back. The unnamed register still receives a copy, so p would also work, but this lesson is about choosing the register on purpose.',
    keys: ['"', 'a', 'y', 'y', 'j', 'j', '"', 'a', 'p'],
    file: 'scratch.ts',
    content: 'alpha\nbeta\ngamma',
    cursor: { line: 0, col: 0 },
    project: false,
    enable: {},
    goal: all([
      { type: 'buffer', text: 'alpha\nbeta\ngamma\nalpha' },
      { type: 'event', name: 'reg:a' },
    ]),
  },
  {
    id: 'macro',
    chapter: 'Power',
    title: 'Macros',
    objective: 'Record a macro that strips foo, then play it on the other lines.',
    explanation:
      'qa starts recording into register a. q stops. @a plays it. Record the change and the motion to the next line, so each play both edits and advances. @@ would replay the last macro.',
    keys: ['q', 'a', 'd', 'w', 'j', 'q', '@', 'a', '@', 'a'],
    file: 'scratch.ts',
    content: 'foo alpha\nfoo beta\nfoo gamma',
    cursor: { line: 0, col: 0 },
    project: false,
    enable: {},
    goal: all([
      { type: 'buffer', text: 'alpha\nbeta\ngamma' },
      { type: 'event', name: 'macro:play' },
    ]),
  },
  {
    id: 'which-key',
    chapter: 'Finding',
    title: 'which-key',
    objective: 'Open the find-files menu from the leader key.',
    explanation:
      'Space is the leader. which-key shows the groups that follow it, so you do not have to memorize every mapping. f is find. f again is files. The menu is the plugin: read it, then press the next key.',
    keys: ['<Space>', 'f', 'f'],
    file: 'src/main.ts',
    cursor: { line: 0, col: 0 },
    project: true,
    enable: { leader: true, telescope: true },
    goal: { type: 'event', name: 'telescope:files' },
  },
  {
    id: 'files',
    chapter: 'Finding',
    title: 'Telescope files',
    objective: 'Open src/util.ts.',
    explanation:
      'Space f f opens the file picker. Type until one file is left, then Enter opens it. Telescope is insert-like: the letters filter the list. Ctrl-n and Ctrl-p move the selection when several rows match. Esc closes the picker.',
    keys: ['<Space>', 'f', 'f', 'u', 't', 'i', 'l', '<CR>'],
    file: 'src/main.ts',
    cursor: { line: 0, col: 0 },
    project: true,
    enable: {},
    goal: { type: 'event', name: 'telescope:open:src/util.ts' },
  },
  {
    id: 'grep',
    chapter: 'Finding',
    title: 'Live grep',
    objective: 'Jump to the trim() call.',
    explanation:
      'Space f g searches the text of every file. The query is plain text. Enter opens the selected line. Use this when you know a string and not the filename.',
    keys: ['<Space>', 'f', 'g', 't', 'r', 'i', 'm', '<CR>'],
    file: 'src/main.ts',
    cursor: { line: 0, col: 0 },
    project: true,
    enable: {},
    goal: all([
      { type: 'event', name: 'telescope:grep' },
      { type: 'file', path: 'src/util.ts' },
    ]),
  },
  {
    id: 'buffers',
    chapter: 'Finding',
    title: 'Buffers',
    objective: 'Switch to src/user.ts.',
    explanation:
      'A buffer is a file you have open. Space f b lists them. Filtering works the same way as file search. Switching buffers is how you move around a project you are already in.',
    keys: ['<Space>', 'f', 'b', 'u', 's', 'e', 'r', '<CR>'],
    file: 'src/main.ts',
    cursor: { line: 0, col: 0 },
    buffers: ['src/main.ts', 'src/util.ts', 'src/user.ts'],
    project: true,
    enable: {},
    goal: all([
      { type: 'event', name: 'telescope:buffers' },
      { type: 'file', path: 'src/user.ts' },
    ]),
  },
  {
    id: 'oil-rename',
    chapter: 'Files',
    title: 'oil rename',
    objective: 'Rename user.ts to person.ts.',
    explanation:
      '- opens oil.nvim on the current directory. The directory is a buffer: cc replaces a filename, and :w applies the edit. A changed line is a rename. Esc leaves insert mode before you write.',
    keys: ['-', 'j', 'j', 'c', 'c', 'p', 'e', 'r', 's', 'o', 'n', '.', 't', 's', '<Esc>', ':', 'w', '<CR>'],
    file: 'src/main.ts',
    cursor: { line: 0, col: 0 },
    project: true,
    enable: { oil: true },
    goal: all([
      { type: 'fileExists', path: 'src/person.ts' },
      { type: 'fileMissing', path: 'src/user.ts' },
    ]),
  },
  {
    id: 'oil-create',
    chapter: 'Files',
    title: 'oil create',
    objective: 'Create src/notes.ts.',
    explanation:
      'In an oil buffer, o opens a new line, the same as in any file. Type the filename, leave insert mode, and :w creates the file. A deleted line would delete the file. The directory is edited with ordinary Neovim.',
    keys: ['-', 'o', 'n', 'o', 't', 'e', 's', '.', 't', 's', '<Esc>', ':', 'w', '<CR>'],
    file: 'src/main.ts',
    cursor: { line: 0, col: 0 },
    project: true,
    enable: {},
    goal: { type: 'fileExists', path: 'src/notes.ts' },
  },
  {
    id: 'surround-add',
    chapter: 'Editing',
    title: 'Add surrounds',
    objective: 'Wrap Ada in double quotes.',
    explanation:
      'ys adds a surround around a motion or text object. ysiw" wraps the inner word in quotes. yss" wraps the line. The pair is the last key: ", \', ), or }.',
    keys: ['f', 'A', 'y', 's', 'i', 'w', '"'],
    file: 'scratch.ts',
    content: 'const name = Ada',
    cursor: { line: 0, col: 0 },
    project: false,
    enable: { surround: true },
    goal: all([
      { type: 'buffer', text: 'const name = "Ada"' },
      { type: 'event', name: 'surround:add' },
    ]),
  },
  {
    id: 'surround-change',
    chapter: 'Editing',
    title: 'Change surrounds',
    objective: 'Turn the double quotes into single quotes.',
    explanation:
      'cs changes one surround for another. cs"\' replaces double quotes with single quotes. The cursor can be on the text inside. You do not retype the word.',
    keys: ['f', 'A', 'c', 's', '"', "'"],
    file: 'scratch.ts',
    content: 'const name = "Ada"',
    cursor: { line: 0, col: 0 },
    project: false,
    enable: {},
    goal: all([
      { type: 'buffer', text: "const name = 'Ada'" },
      { type: 'event', name: 'surround:change' },
    ]),
  },
  {
    id: 'surround-delete',
    chapter: 'Editing',
    title: 'Delete surrounds',
    objective: 'Remove the quotes around Ada.',
    explanation:
      'ds deletes a surround. ds" removes a pair of double quotes. ds( removes parentheses. The text inside stays. This is the inverse of ys.',
    keys: ['f', 'A', 'd', 's', '"'],
    file: 'scratch.ts',
    content: 'const name = "Ada"',
    cursor: { line: 0, col: 0 },
    project: false,
    enable: {},
    goal: all([
      { type: 'buffer', text: 'const name = Ada' },
      { type: 'event', name: 'surround:delete' },
    ]),
  },
  {
    id: 'flash',
    chapter: 'Editing',
    title: 'flash.nvim',
    objective: 'Jump to the T.',
    explanation:
      's starts a flash jump. Type the character you see, then the label that appears on it. Labels are home-row keys. The jump replaces a long chain of w or f when the target is unique enough to see.',
    keys: ['s', 'T', 'a'],
    file: 'scratch.ts',
    content: 'alpha beta TARGET gamma',
    cursor: { line: 0, col: 0 },
    project: false,
    enable: { flash: true },
    goal: all([
      { type: 'cursor', line: 0, col: 11 },
      { type: 'event', name: 'flash:jump' },
    ]),
  },
  {
    id: 'hunks',
    chapter: 'Git',
    title: 'gitsigns',
    objective: 'Stage the changed hunk.',
    explanation:
      ']c jumps to the next hunk, [c to the previous one. The sign column marks it. Space h s stages the hunk under the cursor. Space h p previews the diff, and Space h b shows blame for the line.',
    keys: [']', 'c', '<Space>', 'h', 's'],
    file: 'src/util.ts',
    cursor: { line: 0, col: 0 },
    project: true,
    enable: { gitsigns: true },
    goal: { type: 'event', name: 'gitsigns:stage' },
  },
  {
    id: 'hover',
    chapter: 'LSP',
    title: 'Hover',
    objective: 'Read the type of greet.',
    explanation:
      'K asks the language server what is under the cursor. The answer opens in a float: the signature, and nothing more. Esc or the next motion closes it. Hover is how you check a name without jumping away.',
    keys: ['K'],
    file: 'src/main.ts',
    cursor: POS.greetCall,
    project: true,
    enable: { lsp: true },
    goal: { type: 'event', name: 'lsp:hover' },
  },
  {
    id: 'definition',
    chapter: 'LSP',
    title: 'Go to definition',
    objective: 'Jump to where greet is defined.',
    explanation:
      'gd jumps to the definition of the symbol under the cursor, even in another file. The cursor should land on the name. Come back the ordinary way, or with Ctrl-o in real Neovim. Here, the jump itself is the lesson.',
    keys: ['g', 'd'],
    file: 'src/main.ts',
    cursor: POS.greetCall,
    project: true,
    enable: {},
    goal: all([
      { type: 'file', path: 'src/util.ts' },
      { type: 'cursor', line: POS.greetDef.line, col: POS.greetDef.col },
    ]),
  },
  {
    id: 'references',
    chapter: 'LSP',
    title: 'References',
    objective: 'Open references and jump to the definition.',
    explanation:
      'gr lists every reference, with the definition first. Move with j and k, then Enter jumps. It is the Telescope-shaped view of “who uses this”. Start from a use, not from memory of the filename.',
    keys: ['g', 'r', '<CR>'],
    file: 'src/util.ts',
    cursor: POS.formatRef,
    project: true,
    enable: {},
    goal: all([
      { type: 'event', name: 'lsp:ref-jump' },
      { type: 'cursor', line: POS.formatDef.line, col: POS.formatDef.col },
    ]),
  },
  {
    id: 'rename',
    chapter: 'LSP',
    title: 'Rename',
    objective: 'Rename greet to welcome.',
    explanation:
      'Space r n renames the symbol under the cursor everywhere in the project. The prompt starts with the old name. Ctrl-u clears it. Type the new name and press Enter. The identifier changes. The surrounding code does not.',
    keys: ['<Space>', 'r', 'n', '<C-u>', 'w', 'e', 'l', 'c', 'o', 'm', 'e', '<CR>'],
    file: 'src/util.ts',
    cursor: POS.greetDef,
    project: true,
    enable: {},
    goal: all([
      { type: 'includes', text: 'function welcome' },
      { type: 'event', name: 'lsp:rename' },
    ]),
  },
  {
    id: 'diagnostics',
    chapter: 'LSP',
    title: 'Diagnostics',
    objective: 'Jump to the warning.',
    explanation:
      ']d jumps to the next diagnostic and opens its message. [d jumps backward. The sign column shows W or E, and the text is underlined. Read the float before you edit. The warning in this file is an unused binding.',
    keys: [']', 'd'],
    file: 'src/main.ts',
    cursor: { line: 0, col: 0 },
    project: true,
    enable: {},
    goal: all([
      { type: 'event', name: 'lsp:diagnostic' },
      { type: 'cursor', line: POS.unused.line, col: POS.unused.col },
    ]),
  },
  {
    id: 'completion',
    chapter: 'Syntax',
    title: 'blink.cmp',
    objective: 'Accept formatName from the menu.',
    explanation:
      'In insert mode, blink.cmp opens when the prefix matches a completion. Ctrl-n and Ctrl-p move. Ctrl-y accepts the selected row. Ctrl-e dismisses the menu. The first row is not always the one you want.',
    keys: ['<C-n>', '<C-y>'],
    file: 'scratch.ts',
    content: 'const label = for',
    cursor: { line: 0, col: 'const label = for'.length },
    mode: 'insert',
    project: false,
    enable: { blink: true },
    goal: all([
      { type: 'includes', text: 'formatName' },
      { type: 'event', name: 'complete:accept' },
    ]),
  },
  {
    id: 'function-object',
    chapter: 'Syntax',
    title: 'Function object',
    objective: 'Delete the formatName function.',
    explanation:
      'Treesitter text objects use the syntax tree. daf deletes a function, dif deletes its body and leaves the braces. The cursor can be anywhere inside. greet should still be there when formatName is gone.',
    keys: ['d', 'a', 'f'],
    file: 'src/util.ts',
    cursor: POS.formatBody,
    project: true,
    enable: { treesitter: true },
    goal: all([
      { type: 'excludes', text: 'function formatName' },
      { type: 'includes', text: 'function greet' },
    ]),
  },
  {
    id: 'argument-object',
    chapter: 'Syntax',
    title: 'Argument object',
    objective: 'Change the parameter to person: User.',
    explanation:
      'ia is the inside of an argument, aa includes the commas around it. cia deletes the parameter and enters insert. Type the replacement, then Esc. This is the same text-object grammar, aimed at the syntax tree instead of quotes.',
    keys: ['c', 'i', 'a', 'p', 'e', 'r', 's', 'o', 'n', ':', ' ', 'U', 's', 'e', 'r', '<Esc>'],
    file: 'src/util.ts',
    cursor: POS.formatParam,
    project: true,
    enable: {},
    goal: { type: 'includes', text: 'formatName(person: User)' },
  },
]

export function lessonIndex(id: string): number {
  const index = LESSONS.findIndex((lesson) => lesson.id === id)
  return index < 0 ? 0 : index
}

export function lessonById(id: string): Lesson {
  return LESSONS[lessonIndex(id)] ?? LESSONS[0]
}
